// Copyright (c) 2022 Twigex, SIA.
// SPDX-License-Identifier: AGPL-3.0-only

// A catalog of popular formulas for a formula editor
export const POPULAR_FORMULAS = [
    // Math / Aggregate
    {
        name: "SUM",
        label: "SUM (add numbers)",
        sig: "SUM(...numbers)",
        desc: "Adds all numbers together. Ignores empty/non-numeric values.",
        arity: "variadic",
        argType: "number",
        out: "number",
    },
    {
        name: "AVERAGE",
        label: "AVERAGE (mean)",
        sig: "AVERAGE(...numbers)",
        desc: "Arithmetic mean of the inputs.",
        arity: "variadic",
        argType: "number",
        out: "number",
    },
    {
        name: "PRODUCT",
        label: "PRODUCT (multiply)",
        sig: "PRODUCT(...numbers)",
        desc: "Multiplies all numbers together.",
        arity: "variadic",
        argType: "number",
        out: "number",
    },
    {
        name: "MIN",
        label: "MIN (smallest)",
        sig: "MIN(...numbers)",
        desc: "Returns the smallest number.",
        arity: "variadic",
        argType: "number",
        out: "number",
    },
    {
        name: "MAX",
        label: "MAX (largest)",
        sig: "MAX(...numbers)",
        desc: "Returns the largest number.",
        arity: "variadic",
        argType: "number",
        out: "number",
    },
    {
        name: "ROUND",
        label: "ROUND(number, digits)",
        sig: "ROUND(number, digits)",
        desc: "Rounds a number to a given number of decimal places.",
        arity: 2,
        args: [
            { kind: "field", type: "number", label: "Number (field)" },
            { kind: "const", type: "number", label: "Digits", default: 0 },
        ],
        out: "number",
    },
    {
        name: "ROUNDUP",
        label: "ROUNDUP(number, digits)",
        sig: "ROUNDUP(number, digits)",
        desc: "Rounds away from zero to the specified decimals.",
        arity: 2,
        args: [
            { kind: "field", type: "number", label: "Number (field)" },
            { kind: "const", type: "number", label: "Digits", default: 0 },
        ],
        out: "number",
    },
    {
        name: "ROUNDDOWN",
        label: "ROUNDDOWN(number, digits)",
        sig: "ROUNDDOWN(number, digits)",
        desc: "Rounds toward zero to the specified decimals.",
        arity: 2,
        args: [
            { kind: "field", type: "number", label: "Number (field)" },
            { kind: "const", type: "number", label: "Digits", default: 0 },
        ],
        out: "number",
    },
    {
        name: "ABS",
        label: "ABS(number)",
        sig: "ABS(number)",
        desc: "Absolute value (makes number non-negative).",
        arity: 1,
        args: [{ kind: "field", type: "number", label: "Number (field)" }],
        out: "number",
    },
    {
        name: "POWER",
        label: "POWER(base, exponent)",
        sig: "POWER(base, exponent)",
        desc: "Exponentiation: base^exponent.",
        arity: 2,
        args: [
            { kind: "field", type: "number", label: "Base (field)" },
            { kind: "const", type: "number", label: "Exponent", default: 2 },
        ],
        out: "number",
    },

    // Date / Time
    {
        name: "TODAY",
        label: "TODAY()",
        sig: "TODAY()",
        desc: "Current date (no time).",
        arity: 0,
        out: "date",
    },
    {
        name: "NOW",
        label: "NOW()",
        sig: "NOW()",
        desc: "Current date & time.",
        arity: 0,
        out: "date",
    },
    {
        name: "DATE",
        label: "DATE(year, month, day)",
        sig: "DATE(year, month, day)",
        desc: "Constructs a date from parts.",
        arity: 3,
        args: [
            { kind: "const", type: "number", label: "Year" },
            { kind: "const", type: "number", label: "Month (1-12)" },
            { kind: "const", type: "number", label: "Day (1-31)" },
        ],
        out: "date",
    },
    {
        name: "YEAR",
        label: "YEAR(date)",
        sig: "YEAR(date)",
        desc: "Extracts the year from a date.",
        arity: 1,
        args: [{ kind: "field", type: "date", label: "Date (field)" }],
        out: "number",
    },
    {
        name: "MONTH",
        label: "MONTH(date)",
        sig: "MONTH(date)",
        desc: "Extracts the month number (1–12).",
        arity: 1,
        args: [{ kind: "field", type: "date", label: "Date (field)" }],
        out: "number",
    },
    {
        name: "DAY",
        label: "DAY(date)",
        sig: "DAY(date)",
        desc: "Extracts the day of month (1–31).",
        arity: 1,
        args: [{ kind: "field", type: "date", label: "Date (field)" }],
        out: "number",
    },
    {
        name: "DATEDIF",
        label: 'DATEDIF(start, end, "D/M/Y")',
        sig: "DATEDIF(start_date, end_date, unit)",
        desc: "Difference between two dates in days (D), months (M), or years (Y).",
        arity: 3,
        args: [
            { kind: "field", type: "date", label: "Start date (field)" },
            { kind: "field", type: "date", label: "End date (field)" },
            { kind: "const", type: "text-const", label: 'Unit ("D","M","Y")', default: "D" },
        ],
        out: "number",
    },
    {
        name: "WEEKDAY",
        label: "WEEKDAY(date, [type])",
        sig: "WEEKDAY(date, [type])",
        desc: "Day of week number; type controls numbering scheme.",
        arity: 2,
        args: [
            { kind: "field", type: "date", label: "Date (field)" },
            { kind: "const", type: "number", label: "Type (optional)", default: 1 },
        ],
        out: "number",
    },
];
